---
version: '3.0'

services:
  mymtn_shop:
    image: mymtnregistry.azurecr.io/mymtnshop:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=mymtnshop
      - DB_HOST="mongodb_mongodb_1:27017"
    ports:
      - 0.0.0.0:8085:8085
    networks:
      - mymtnshop
networks:
  mymtnshop: