apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextgen-dev-cd-role
  namespace: nextgen-dev
rules:
- apiGroups:
  - ""
  resources: ["configmaps", "services", "persistentvolumeclaims"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups:
  - "apps"
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextgen-dev-cd-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextgen-dev-cd-role
subjects:
- kind: ServiceAccount
  name: nextgen-dev-cd